[package]
name = "def"
version = "0.1.0"
authors = ["pteromys <pteromys@gmail.com>"]
publish = false

[build-dependencies]
cc="*"

[dependencies]
bytes = { version = "1", features = ["serde"] }
clap = { version = "4.5.4", features = ["derive", "unicode", "wrap_help"] }
console = "0.15"
regex = "1.10"  # match ripgrep's default engine since we shell out to ripgrep
tree-sitter = "0.20"
tree-sitter-c = "0.20"
tree-sitter-cpp = "0.20"
tree-sitter-go = "0.20"
tree-sitter-javascript = "0.20"
tree-sitter-python = "0.20"
tree-sitter-rust = "0.20"
tree-sitter-typescript = "0.20"

[[bin]]
path = "src/def.rs"
name = "def"
